# MkDocs configuration for QtPlugin documentation
site_name: QtPlugin Documentation
site_description: Comprehensive documentation for the QtPlugin library - a modern, pure C++ plugin system for Qt applications
site_author: QtPlugin Development Team
site_url: https://qtplugin.dev

# Repository information
repo_name: qt-plugin-sample
repo_url: https://github.com/example/qt-plugin-sample
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 QtPlugin Development Team

# Configuration
theme:
  name: material
  language: en
  
  # Color scheme
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  
  # Custom icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    
  # Logo and favicon
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - awesome-pages
  - include-markdown
  - macros
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - redirects:
      redirect_maps:
        'index.md': 'getting-started/overview.md'

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - tables
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: example
      repo: qt-plugin-sample
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/code.css

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra configuration
extra:
  version:
    provider: mike
    default: stable
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/example/qt-plugin-sample
      name: GitHub Repository
    - icon: fontawesome/solid/globe
      link: https://qtplugin.dev
      name: Official Website
  
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/example/qt-plugin-sample/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you found lacking</a>.

# Watch additional files
watch:
  - includes/
  - lib/include/
  - examples/

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
